# Generated by Django 5.2.1 on 2025-12-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
