# Generated by Django 5.2.1 on 2025-12-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_department_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='age',
        ),
        migrations.AddField(
            model_name='department',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
