# Generated by Django 5.2.1 on 2025-12-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_department_age_department_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='year',
            field=models.IntegerField(),
        ),
    ]
