# Generated by Django 5.2.1 on 2026-01-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_department_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('p_number', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=50)),
                ('yostudy', models.CharField(max_length=10)),
                ('rollnumber', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('technical_Skills', models.CharField(max_length=100)),
                ('preferred_mode', models.CharField(max_length=20)),
                ('resume_upload', models.FileField(upload_to='resumes/')),
                ('about_yourself', models.TextField()),
                ('aggree', models.BooleanField()),
            ],
        ),
    ]
