# Generated by Django 4.2 on 2026-01-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('cse', 'CSE'), ('ece', 'ECE'), ('mech', 'MECH'), ('it', 'IT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('AndhraPradesh', 'Andhra Pradesh'), ('Telangana', 'Telangana'), ('Karnataka', 'Karnataka'), ('Tamilnadu', 'Tamil Nadu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='technical_Skills',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('c++', 'C++'), ('webdev', 'Web Development')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='yostudy',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=10),
        ),
    ]
